package com.quarkdown.amber.plugin.wiring

import org.gradle.api.Project
import org.jetbrains.kotlin.gradle.dsl.KotlinProjectExtension
import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask
import java.io.File

/**
 * How Amber plugs into a project, which depends on the Kotlin plugin the project applies: the
 * source set that is processed, the configurations Amber's artifacts belong to, and where the
 * processor's output is picked up from.
 *
 * Both shapes read the project's source sets through the Kotlin extension, which every Kotlin
 * plugin provides: what genuinely differs is only what KSP names and where it writes.
 *
 * @param sourceSetName Source set the processor reads from, and generates into.
 * @param generatedSourcesDirectory Directory KSP generates sources into, relative to the project.
 * @param annotationsConfiguration Configuration the annotations artifact is added to.
 * @param processorConfiguration Configuration the KSP processor is added to.
 * @param processingTask Task generating the sources every compilation then compiles, when KSP does
 *                       not wire it into them itself. Null when the processed source set is the
 *                       only consumer of its own generated sources.
 */
class AmberWiring(
    val sourceSetName: String,
    val generatedSourcesDirectory: String,
    val annotationsConfiguration: String,
    val processorConfiguration: String,
    private val processingTask: String? = null,
) {
    /** Makes the sources generated by the processor part of the project's own sources. */
    fun registerGeneratedSources(project: Project) {
        project.kotlinExtension?.sourceSets?.named(sourceSetName) {
            kotlin.srcDir(generatedSourcesDirectory)
        }

        // Compilations other than the processed one consume the generated sources, hence must wait for them.
        processingTask?.let { task ->
            project.tasks.withType(KotlinCompilationTask::class.java).configureEach {
                if (name != task) {
                    dependsOn(task)
                }
            }
        }
    }

    /** Directories `@ExportResource` may read resources from: those of the processed source set. */
    fun resourceRoots(project: Project): List<File> =
        project.kotlinExtension
            ?.sourceSets
            ?.findByName(sourceSetName)
            ?.resources
            ?.srcDirs
            ?.toList()
            .orEmpty()

    private val Project.kotlinExtension: KotlinProjectExtension?
        get() = extensions.findByType(KotlinProjectExtension::class.java)

    companion object {
        /** Wiring for a Kotlin/JVM project: one `main` source set, processed by the single `ksp` configuration. */
        val JVM =
            AmberWiring(
                sourceSetName = "main",
                generatedSourcesDirectory = "build/generated/ksp/main/kotlin",
                annotationsConfiguration = "implementation",
                processorConfiguration = "ksp",
            )

        /**
         * Wiring for a Kotlin Multiplatform project: only the common source set is processed, once,
         * and the resulting sources become part of it, so that every target compiles the same
         * generated declarations and common code can call them. As a consequence, annotations
         * placed in platform-specific source sets are not picked up.
         */
        val MULTIPLATFORM =
            AmberWiring(
                sourceSetName = "commonMain",
                generatedSourcesDirectory = "build/generated/ksp/metadata/commonMain/kotlin",
                annotationsConfiguration = "commonMainImplementation",
                processorConfiguration = "kspCommonMainMetadata",
                processingTask = "kspCommonMainKotlinMetadata",
            )
    }
}
