package com.quarkdown.automerge.processor

import com.quarkdown.automerge.annotations.AutoMerge

/**
 * Internal constants used by the AutoMerge KSP processor.
 */
internal object GenerationConstants {
    /** Standard header placed at the top of generated files. */
    const val GENERATED_HEADER: String = "// Generated by automerge KSP processor. Do not edit."

    /** Name of the generated merge function. */
    const val MERGE_FUNCTION_NAME: String = "merge"

    /** Name of the parameter representing the other instance to merge with. */
    const val MERGE_PARAMETER_NAME: String = "other"

    /** Indentation string used in generated code. */
    const val INDENT: String = "    "

    /** Fully-qualified name of the AutoMerge annotation. */
    val ANNOTATION_FQN: String = AutoMerge::class.java.run { "$packageName.$simpleName" }

    /** Simple name of the AutoMerge annotation. */
    val ANNOTATION_SIMPLE_NAME: String = AutoMerge::class.java.simpleName
}
