package com.quarkdown.automerge.processor

/**
 * Internal constants used by the AutoMerge KSP processor.
 */
internal object GenerationConstants {
    /** Standard header placed at the top of generated files. */
    const val GENERATED_HEADER: String = "// Generated by automerge KSP processor. Do not edit."

    /** File-level suppress annotation. */
    const val SUPPRESS_ANNOTATION: String =
        """@file:Suppress("ktlint", "RedundantNullableReturnType", "UNUSED_PARAMETER", "LocalVariableName")"""

    /** Indentation used in generated code. */
    const val INDENT: String = "    "
}
