name: CI

on:
  push:
    branches: ["**"]
    paths-ignore:
      - '*.md'
      - '**/README.md'
      - 'version.txt'
      - 'LICENSE'
      - '.github/FUNDING.yml'
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew --no-daemon test
